-- Schema de referência para ambiente novo/local. Não execute sobre o banco de produção já criado.
PRAGMA foreign_keys = ON;
CREATE TABLE categories (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE, slug TEXT NOT NULL UNIQUE, description TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE tags (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE, slug TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE posts (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, excerpt TEXT NOT NULL, content_markdown TEXT NOT NULL DEFAULT '', content_html TEXT, status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','scheduled','published','archived')), author_name TEXT NOT NULL DEFAULT 'Ryuzen Anime Hub', category_id INTEGER, cover_image_url TEXT, cover_alt TEXT, cover_credit TEXT, cover_source_url TEXT, social_image_url TEXT, seo_title TEXT, seo_description TEXT, canonical_url TEXT, featured INTEGER NOT NULL DEFAULT 0 CHECK (featured IN (0,1)), published_at TEXT, scheduled_at TEXT, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL);
CREATE TABLE post_tags (post_id INTEGER NOT NULL, tag_id INTEGER NOT NULL, PRIMARY KEY (post_id, tag_id), FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE, FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE);
CREATE TABLE post_revisions (id INTEGER PRIMARY KEY AUTOINCREMENT, post_id INTEGER NOT NULL, title TEXT NOT NULL, excerpt TEXT NOT NULL, content_markdown TEXT NOT NULL, revision_note TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE);
CREATE TABLE post_images (id INTEGER PRIMARY KEY AUTOINCREMENT, post_id INTEGER NOT NULL, image_url TEXT NOT NULL, alt_text TEXT NOT NULL, caption TEXT, credit_text TEXT, source_url TEXT, placement TEXT NOT NULL DEFAULT 'inline' CHECK (placement IN ('inline','gallery','highlight')), position_order INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE);
CREATE INDEX idx_posts_slug ON posts(slug); CREATE INDEX idx_posts_status_published ON posts(status, published_at); CREATE INDEX idx_posts_category ON posts(category_id); CREATE INDEX idx_post_images_post_id ON post_images(post_id); CREATE INDEX idx_post_images_post_position ON post_images(post_id, position_order);
INSERT INTO categories (name,slug,description) VALUES ('Animes','animes','Notícias, listas e recomendações sobre animes.'), ('Guias','guias','Conteúdos explicativos e guias para leitores.'), ('Lançamentos','lancamentos','Estreias, confirmações e calendários de lançamentos.');
